apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-scheduler-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: task-scheduler-backend
        image: naimbiswas/task-scheduler-backend:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
